### ISSUE TITLE
Panicked at Result unwrap bug

### ISSUE THREAD

**Issue by fgadaleta** [lemunozm/message-io#119] opened 2022-03-16 14:46 UTC
Reproducibility

While running the discovery server (as in the examples), if I disconnect with some peers, I get a panic from

`                    let addr = self.stream.peer_addr().unwrap();`
in `message-io-0.14.4/src/adapters/framed_tcp.rs:65:56`

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }', /home/frag/.cargo/registry/src/github.com-1ecc6299db9ec823/message-io-0.14.4/src/adapters/framed_tcp.rs:65:56
```

**Comment by lemunozm** [comment] 2022-03-16 17:51
Hi, I fixed the issue here https://github.com/lemunozm/message-io/pull/120, but I would like to reproduce your error because I never got it. Could you please give some feedback about: 
- Does it happen always you disconnect an endpoint or sometimes? 
- Are you transferring big messages or saturating the network? 
- Are you testing both endpoints in localhost?

Thanks!

**Comment by fgadaleta** [comment] 2022-03-17 09:45
It doesn't happen all the time.
I think that when I get closer to saturating the network it happens more often and definitely when the clients disconnect (or i kill them).

**Comment by dovahcrow** [comment] 2022-03-17 20:30
Yep I got the same issue
panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }', /home
/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/message-io-0.14.4/src/adapters/framed_tcp.rs:65:56

**Comment by lemunozm** [comment] 2022-03-17 20:51
I updated `message-io` to `0.14.5` which solves the issue.

Thanks for reporting!

**Closed** 2022-03-17 20:52 UTC
Labels: bug
